import {
  BarChart3,
  BellRing,
  Camera,
  Coins,
  Gift,
  Handshake,
  Settings,
  Shield,
  TrendingUp,
  Trophy,
  Users,
} from "lucide-react";
import { ROLE_GROUPS } from "@/lib/authorization";
import type { NavItem } from "@/components/layout/navigation/types";

export const adminNavItems: NavItem[] = [
  {
    href: "/admin",
    label: "Visao Geral",
    icon: Shield,
    roles: [...ROLE_GROUPS.tenantAdmin],
    policy: "ADMIN_ONLY",
    section: "home",
    quickSearch: true,
  },
  {
    href: "/admin/eventos",
    label: "Provas",
    icon: Trophy,
    roles: [...ROLE_GROUPS.tenantAdmin],
    policy: "ADMIN_ONLY",
    section: "events",
    quickSearch: true,
  },
  {
    href: "/admin/atletas",
    label: "Atletas",
    icon: Users,
    roles: [...ROLE_GROUPS.tenantAdmin],
    policy: "ADMIN_ONLY",
    section: "admin",
    quickSearch: true,
  },
  {
    href: "/admin/financeiro",
    label: "Financeiro",
    icon: BarChart3,
    roles: [...ROLE_GROUPS.tenantFinance],
    policy: "FINANCE_AREA",
    section: "finance",
    quickSearch: true,
  },
  {
    href: "/admin/recompensas",
    label: "Catalogo de Recompensas",
    icon: Gift,
    roles: [...ROLE_GROUPS.tenantAdmin],
    policy: "ADMIN_ONLY",
    section: "points",
    quickSearch: true,
  },
  {
    href: "/admin/resgates",
    label: "Resgates",
    icon: Coins,
    roles: [...ROLE_GROUPS.tenantAdmin],
    policy: "ADMIN_ONLY",
    section: "points",
    quickSearch: true,
  },
  {
    href: "/admin/pontos",
    label: "Pontos e Auditoria",
    icon: TrendingUp,
    roles: [...ROLE_GROUPS.tenantAdmin],
    policy: "ADMIN_ONLY",
    section: "points",
    quickSearch: true,
  },
  {
    href: "/admin/avisos",
    label: "Avisos",
    icon: BellRing,
    roles: [...ROLE_GROUPS.tenantAdmin],
    policy: "NOTICES_MANAGE",
    section: "communication",
    quickSearch: true,
  },
  {
    href: "/admin/configuracoes",
    label: "Configuracoes",
    icon: Settings,
    roles: [...ROLE_GROUPS.tenantAdmin],
    policy: "ADMIN_ONLY",
    section: "admin",
    quickSearch: true,
  },
  {
    href: "/admin/fotos",
    label: "Fotos",
    icon: Camera,
    roles: [...ROLE_GROUPS.tenantAdmin],
    policy: "ADMIN_ONLY",
    section: "points",
    quickSearch: true,
  },
  {
    href: "/admin/patrocinadores",
    label: "Patrocinadores",
    icon: Handshake,
    roles: [...ROLE_GROUPS.tenantAdmin],
    policy: "ADMIN_ONLY",
    section: "finance",
    quickSearch: true,
  },
];
