import {
  BellRing,
  CalendarDays,
  Camera,
  ClipboardList,
  Coins,
  Dumbbell,
  Footprints,
  Gift,
  Handshake,
  Heart,
  TrendingUp,
  Trophy,
  Wallet,
} from "lucide-react";
import { ROLE_GROUPS } from "@/lib/authorization";
import type { NavItem } from "@/components/layout/navigation/types";

export const athleteNavItems: NavItem[] = [
  {
    href: "/",
    label: "Atleta",
    icon: Footprints,
    roles: [...ROLE_GROUPS.athlete],
    policy: "ATHLETE_AREA",
    section: "home",
    quickSearch: true,
  },
  {
    href: "/provas",
    label: "Provas",
    icon: Trophy,
    roles: [...ROLE_GROUPS.athlete],
    policy: "ATHLETE_AREA",
    section: "events",
    quickSearch: true,
  },
  {
    href: "/minhas-inscricoes",
    label: "Inscrições e Pagamentos",
    icon: ClipboardList,
    roles: [...ROLE_GROUPS.athlete],
    policy: "ATHLETE_AREA",
    section: "events",
    quickSearch: true,
  },
  {
    href: "/financeiro",
    label: "Financeiro",
    icon: Wallet,
    roles: [...ROLE_GROUPS.athlete],
    policy: "ATHLETE_AREA",
    section: "finance",
    quickSearch: true,
  },
  {
    href: "/treinos",
    label: "Treinos",
    icon: Dumbbell,
    roles: [...ROLE_GROUPS.athlete],
    policy: "ATHLETE_AREA",
    section: "home",
    quickSearch: true,
  },
  {
    href: "/calendario",
    label: "Calendário",
    icon: CalendarDays,
    roles: [...ROLE_GROUPS.athlete],
    policy: "ATHLETE_AREA",
    section: "events",
    quickSearch: true,
  },
  {
    href: "/evolucao",
    label: "Evolução e Ranking",
    icon: TrendingUp,
    roles: [...ROLE_GROUPS.athlete],
    policy: "ATHLETE_AREA",
    section: "home",
    quickSearch: true,
  },
  {
    href: "/comunidade",
    label: "Comunidade",
    icon: Heart,
    roles: [...ROLE_GROUPS.athlete],
    policy: "ATHLETE_AREA",
    section: "communication",
    quickSearch: true,
  },
  {
    href: "/avisos",
    label: "Avisos",
    icon: BellRing,
    roles: [...ROLE_GROUPS.athlete],
    policy: "ATHLETE_AREA",
    section: "communication",
    quickSearch: true,
  },
  {
    href: "/fotos",
    label: "Fotos",
    icon: Camera,
    roles: [...ROLE_GROUPS.athlete],
    policy: "ATHLETE_AREA",
    section: "points",
    quickSearch: true,
  },
  {
    href: "/recompensas",
    label: "Recompensas",
    icon: Gift,
    roles: [...ROLE_GROUPS.athlete],
    policy: "ATHLETE_AREA",
    section: "points",
    quickSearch: true,
  },
  {
    href: "/meus-resgates",
    label: "Meus Resgates",
    icon: Coins,
    roles: [...ROLE_GROUPS.athlete],
    policy: "ATHLETE_AREA",
    section: "points",
    quickSearch: true,
  },
  {
    href: "/patrocinadores",
    label: "Patrocinadores",
    icon: Handshake,
    roles: [...ROLE_GROUPS.athlete],
    policy: "ATHLETE_AREA",
    section: "communication",
    quickSearch: true,
  },
];
