import {
  BadgeCheck,
  BellRing,
  Camera,
  Crown,
  Handshake,
  Headphones,
  Megaphone,
  SlidersHorizontal,
  Trophy,
} from "lucide-react";
import type { NavItem } from "@/components/layout/navigation/types";
import { UserRole } from "@/types";

export const extendedNavItems: NavItem[] = [
  {
    href: "/gestor",
    label: "Gestão Geral",
    icon: SlidersHorizontal,
    roles: [UserRole.MANAGER],
    policy: "MANAGER_AREA",
    section: "home",
    quickSearch: true,
  },
  {
    href: "/organizador",
    label: "Operação de Eventos",
    icon: Megaphone,
    roles: [UserRole.ORGANIZER],
    policy: "ORGANIZER_AREA",
    section: "events",
    quickSearch: true,
  },
  {
    href: "/admin/eventos",
    label: "Provas e Check-in",
    icon: Trophy,
    roles: [UserRole.ORGANIZER],
    policy: "ORGANIZER_AREA",
    section: "events",
    quickSearch: true,
  },
  {
    href: "/premium",
    label: "Premium",
    icon: Crown,
    roles: [UserRole.PREMIUM_ATHLETE],
    policy: "PREMIUM_ATHLETE_AREA",
    section: "home",
    quickSearch: true,
  },
  {
    href: "/suporte",
    label: "Suporte",
    icon: Headphones,
    roles: [UserRole.SUPPORT],
    policy: "SUPPORT_AREA",
    section: "admin",
    quickSearch: true,
  },
  {
    href: "/moderador",
    label: "Moderação",
    icon: BadgeCheck,
    roles: [UserRole.MODERATOR],
    policy: "MODERATOR_AREA",
    section: "communication",
    quickSearch: true,
  },
  {
    href: "/admin/avisos",
    label: "Avisos",
    icon: BellRing,
    roles: [UserRole.MODERATOR],
    policy: "NOTICES_MANAGE",
    section: "communication",
    quickSearch: true,
  },
  {
    href: "/admin/fotos",
    label: "Fotos",
    icon: Camera,
    roles: [UserRole.MODERATOR],
    policy: "MODERATOR_AREA",
    section: "communication",
    quickSearch: true,
  },
  {
    href: "/parceiro",
    label: "Parceiro",
    icon: Handshake,
    roles: [UserRole.PARTNER],
    policy: "PARTNER_AREA",
    section: "finance",
    quickSearch: true,
  },
  {
    href: "/admin/patrocinadores",
    label: "Patrocinadores",
    icon: Handshake,
    roles: [UserRole.PARTNER],
    policy: "PARTNER_AREA",
    section: "finance",
    quickSearch: true,
  },
];
