ALTER TYPE "public"."UserRole" ADD VALUE IF NOT EXISTS 'ORGANIZER';
ALTER TYPE "public"."UserRole" ADD VALUE IF NOT EXISTS 'MANAGER';
ALTER TYPE "public"."UserRole" ADD VALUE IF NOT EXISTS 'PREMIUM_ATHLETE';
ALTER TYPE "public"."UserRole" ADD VALUE IF NOT EXISTS 'SUPPORT';
ALTER TYPE "public"."UserRole" ADD VALUE IF NOT EXISTS 'MODERATOR';
ALTER TYPE "public"."UserRole" ADD VALUE IF NOT EXISTS 'PARTNER';
