import type { NotificationChannel, NotificationEventType } from "./types";

export function resolveNotificationTemplateCode(
  eventType: NotificationEventType,
  channel: NotificationChannel,
): string | null {
  const map: Record<string, string> = {
    "NOTICE_PUBLISHED:IN_APP": "NOTICE_PUBLISHED_IN_APP",

    "ATHLETE_REGISTERED:IN_APP": "ATHLETE_REGISTERED_IN_APP",
    "ATHLETE_REGISTERED:EMAIL": "ATHLETE_REGISTERED_EMAIL",
    "ATHLETE_APPROVED:IN_APP": "ATHLETE_APPROVED_IN_APP",
    "ATHLETE_APPROVED:EMAIL": "ATHLETE_APPROVED_EMAIL",
    "ATHLETE_REJECTED:IN_APP": "ATHLETE_REJECTED_IN_APP",
    "ATHLETE_REJECTED:EMAIL": "ATHLETE_REJECTED_EMAIL",

    "EVENT_PUBLISHED:IN_APP": "EVENT_PUBLISHED_IN_APP",
    "EVENT_PUBLISHED:EMAIL": "EVENT_PUBLISHED_EMAIL",
    "EVENT_PUBLISHED:WHATSAPP": "EVENT_PUBLISHED_WHATSAPP",
    "EVENT_UPDATED:IN_APP": "EVENT_UPDATED_IN_APP",
    "EVENT_UPDATED:EMAIL": "EVENT_UPDATED_EMAIL",
    "EVENT_UPDATED:WHATSAPP": "EVENT_UPDATED_WHATSAPP",
    "EVENT_REMINDER_1_DAY:IN_APP": "EVENT_REMINDER_1_DAY_IN_APP",
    "EVENT_REMINDER_1_DAY:SMS": "EVENT_REMINDER_SMS",
    "EVENT_CANCELLED:IN_APP": "EVENT_CANCELLED_IN_APP",
    "EVENT_CANCELLED:EMAIL": "EVENT_CANCELLED_EMAIL",
    "EVENT_CANCELLED:WHATSAPP": "EVENT_CANCELLED_WHATSAPP",

    "TRAINING_REMINDER_2_HOURS:IN_APP": "TRAINING_REMINDER_2_HOURS_IN_APP",
    "TRAINING_REMINDER_2_HOURS:WHATSAPP": "TRAINING_REMINDER_2_HOURS_WHATSAPP",

    "BIRTHDAY_INDIVIDUAL:IN_APP": "BIRTHDAY_INDIVIDUAL_IN_APP",
    "BIRTHDAY_INDIVIDUAL:EMAIL": "BIRTHDAY_INDIVIDUAL_EMAIL",
    "BIRTHDAY_INDIVIDUAL:WHATSAPP": "BIRTHDAY_INDIVIDUAL_WHATSAPP",

    "PAYMENT_PENDING:IN_APP": "PAYMENT_PENDING_IN_APP",
    "PAYMENT_PENDING:EMAIL": "PAYMENT_PENDING_EMAIL",
    "PAYMENT_PENDING:SMS": "PAYMENT_PENDING_SMS",

    "REGISTRATION_CONFIRMED:IN_APP": "REGISTRATION_CONFIRMED_IN_APP",
    "REGISTRATION_CONFIRMED:EMAIL": "REGISTRATION_CONFIRMED_EMAIL",
    "POINTS_CREDITED:IN_APP": "POINTS_CREDITED_IN_APP",
    "POINTS_CREDITED:EMAIL": "POINTS_CREDITED_EMAIL",
    "POINTS_EXPIRING_SOON:IN_APP": "POINTS_EXPIRING_SOON_IN_APP",
    "POINTS_EXPIRING_SOON:EMAIL": "POINTS_EXPIRING_SOON_EMAIL",
    "REWARD_REDEEMED:IN_APP": "REWARD_REDEEMED_IN_APP",
    "REWARD_REDEEMED:EMAIL": "REWARD_REDEEMED_EMAIL",
  };

  return map[`${eventType}:${channel}`] ?? null;
}
